## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [10]:
import numpy as np


In [3]:
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
n = int(input())
arr = np.array([1, 2, 3]*n)
print(arr)

4
[1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
a = np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
a = np.zeros((10, 10))
a[0,:] = 1
a[9,:] = 1
a[:,0] = 1
a[:,9] = 1

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
n = int(input())
arr = np.zeros((n,n))
for i in range(0, n):
    for j in range(0, n):
        arr[i][j] = i+j
print(arr)

4
[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [9]:
A = [1, 2, 3, 4, 5]
B = [[6], [7], [8], [9], [10]]
C = [[10, 9, 8, 7, 6], [5, 4, 3, 2, 1]]
D = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

print(np.dot(A,B))
print(np.dot(C,B))
print(np.dot(C,D))

[130]
[[310]
 [110]]
[[180 220]
 [ 55  70]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [11]:
c = list(np.cos(np.linspace(0, 1, 20)))
s = list(np.sin(np.linspace(0, 1, 20)))
print(c+s)

[1.0, 0.9986152781425827, 0.9944649474795756, 0.9875605021181478, 0.9779210635311101, 0.9655733276010717, 0.9505514906876966, 0.9328971549228098, 0.9126592129956349, 0.8898937127472434, 0.8646637019492132, 0.8370390536963741, 0.8070962728972044, 0.7749182843977933, 0.7405942033261461, 0.7042190882928544, 0.6658936781316236, 0.625724112908743, 0.5838216399741468, 0.5403023058681398, 0.0, 0.05260728333807213, 0.10506887376594912, 0.15723948186175024, 0.20897462406278547, 0.2601310228046501, 0.3105670033203749, 0.3601428860007191, 0.40872137322898616, 0.4561679296190457, 0.5023511546035125, 0.547143146340223, 0.5904198559291864, 0.6320614309590333, 0.6719525474315213, 0.7099827291448582, 0.7460466536513234, 0.7800444439418607, 0.8118819450498316, 0.8414709848078965]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [12]:
arr = np.random.rand(3, 5)*4 - 1
print(arr)

[[ 2.73261068 -0.06007968  2.59259479  0.04967206  0.36107274]
 [ 0.0554579   1.84391318 -0.95058091  0.29598678  1.05303828]
 [ 1.12176901 -0.14401662 -0.9546152   0.19289396 -0.78037281]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [15]:
print(arr.sum())
print(arr.sum(1))
print(arr.sum(0))
mean = arr.mean(1)
print(mean)
print(arr.var(1))
std = arr.std(1)
print(std)

7.409344169563974
[ 5.67587059  2.29781524 -0.56434166]
[3.90983758 1.63981688 0.68739868 0.5385528  0.63373822]
[ 1.13517412  0.45956305 -0.11286833]
[1.57641157 0.88944046 0.55457803]
[1.2555523  0.94310151 0.74469996]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [16]:
for i in range(0, len(arr)):
    arr[i,:] -= mean[i]
    arr[i,:] /= std[i]
print(arr)

[[ 1.27229791 -0.95197452  1.16078054 -0.8645614  -0.61654252]
 [-0.42848532  1.4678697  -1.4952197  -0.17344502  0.62928034]
 [ 1.65789902 -0.04182663 -1.13031679  0.41058454 -0.89634015]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [18]:
print(arr[arr[:, 2].argsort()])

[[-0.42848532  1.4678697  -1.4952197  -0.17344502  0.62928034]
 [ 1.65789902 -0.04182663 -1.13031679  0.41058454 -0.89634015]
 [ 1.27229791 -0.95197452  1.16078054 -0.8645614  -0.61654252]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [19]:
B = np.dot(np.transpose(arr), arr)
C = np.dot(arr, np.transpose(arr))
print(B)
print(C)

[[ 4.5509708  -1.90950013  0.24358724 -0.34495331 -2.54010459]
 [-1.90950013  3.06264642 -3.25254385  0.55127237  1.54812519]
 [ 0.24358724 -3.25254385  4.86070944 -1.20831823 -0.64343459]
 [-0.34495331  0.55127237 -1.20831823  0.94612926  0.05586992]
 [-2.54010459  1.54812519 -0.64343459  0.05586992  1.57954408]]
[[ 5.         -3.91618166  1.03476588]
 [-3.91618166  5.          0.28302742]
 [ 1.03476588  0.28302742  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [20]:
np.sum(np.diagonal(B)) + np.sum(np.diagonal(C))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [21]:
print(np.linalg.det(B))
print(np.linalg.det(C))
print(np.linalg.matrix_rank(arr))
print(np.linalg.matrix_rank(B))
print(np.linalg.matrix_rank(C))
w_B, v_B = np.linalg.eig(B)
w_C, v_C = np.linalg.eig(C)
print(w_B)
print(w_C)


1.6827690386052412e-31
40.26953949208635
3
3
3
[ 8.98902055e+00  5.13929151e+00  8.71687940e-01 -8.58628396e-16
  5.12443180e-18]
[0.87168794 8.98902055 5.13929151]


In [22]:
np.random.seed(1032201732)

In [23]:
np.random.randint(0, 8,size=1)

array([4])

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [24]:
print('Аналитическое решение интеграла 4: ', np.arctan(np.log(np.e)) - np.arctan(np.log(1)))
print('Аналитическое решение интеграла 9: ', np.pi/(2**(3/2)))

Аналитическое решение интеграла 4:  0.7853981633974483
Аналитическое решение интеграла 9:  1.1107207345395915


In [28]:
def integ4(x):
    return 1/(x*(1+np.log(x)**2))

def integ9(x):
    return 1/ np.sqrt(2+3*x-2*x**2, where = x!=2)

def solution(func,a, b, dx, method):
    n = int((b-a) / dx)
    xx = np.linspace(a, b, n)
    if method == 'rectangular':
        return dx*np.sum(func(xx))
    elif method == 'trapezoid':
        return dx/2*(func(xx[0]) + 2*np.sum(func(xx[1:-1])) + func(xx[-1]))
    elif method == 'simpson':
        return dx/3*(func(xx[0]) + 2*np.sum(func(xx[2:-1:2])) + 4*np.sum(func(xx[1:-2:2])) + func(xx[-1]))
    else:
        return 'Неверный метод'
    
print('Для интеграла 4:', solution(integ4, 1, np.e, 0.0001, 'rectangular'), 'Для интеграла 9:', solution(integ9, 3/4, 2, 0.0001, 'rectangular') )
print('Для интеграла 4:', solution(integ4, 1, np.e, 0.0001, 'trapezoid'), 'Для интеграла 9:', solution(integ9, 3/4, 2, 0.0001, 'trapezoid') )
print('Для интеграла 4:', solution(integ4, 1, np.e, 0.0001, 'simpson'), 'Для интеграла 9:', solution(integ9, 3/4, 2, 0.0001, 'simpson') )

Для интеграла 4: 0.7853742503271548 Для интеграла 9: 1.1041903982773003
Для интеграла 4: 0.7853150533411256 Для интеграла 9: inf
Для интеграла 4: 0.785308921070893 Для интеграла 9: inf


/tmp/ipykernel_3969/2635991828.py:5: RuntimeWarning: overflow encountered in scalar divide
  return 1/ np.sqrt(2+3*x-2*x**2, where = x!=2)
